// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	Id string `form:"id"`
}

type UserInfoResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type ErrJsonResult struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SuccessJsonResult struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpore"`
	RefreshAfter int64  `json:"refreshAfter"`
}
